### ISSUE TITLE
I don't know how to compile this

### ISSUE THREAD

**Issue by JJRcop** [TerryCavanagh/Copycat#1]
Yes maybe this isn't really for the Github issue reports for this repo... OH WELL... Basically I don't know how to compile this. I downloaded Haxe binaries but I don't know what to do to get it to follow copycat.hxproj

It also looks like i need libraries I don't know where to get, so I can't really compile this.

**Comment by JJRcop** [comment]
Oh, I need FlashDevelop

**Comment by TerryCavanagh** [comment]
Glad you figured it out! I'll add a note to the readme!

**Comment by JJRcop** [comment]
Yeah, I don't know what I'm doing.
